; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{0A9B400B-50F7-411C-80D7-2AAE479A0101}
AppName=MediaCreator
AppVersion=2.2
;AppVerName=My Program 1.5
AppPublisher=My Company, Inc.
AppPublisherURL=https://www.example.com/
AppSupportURL=https://www.example.com/
AppUpdatesURL=https://www.example.com/
DefaultDirName={autopf}\MediaCreator
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
OutputDir=D:\development\Installers
OutputBaseFilename=mediacreator_installer
Compression=lzma
SolidCompression=yes
WizardStyle=modern


[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\development\cwp_app\MediaCreator.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\development\cwp_app\*"; DestDir: "{app}";  Excludes: "cwp_app.iss,*.log,.git*,.idea*,.vscode,*\logs,old_ext\*,cwp_sqlite.*,.webcache\*,files\*"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\MediaCreator"; Filename: "{app}\MediaCreator.exe"
Name: "{autodesktop}\MediaCreator"; Filename: "{app}\MediaCreator.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\MediaCreator.exe"; Description: "{cm:LaunchProgram,My MediaCreator}"; Flags: nowait postinstall skipifsilent unchecked
Filename: "{app}\post.bat"; Parameters: """{app}"""; Description: "Config Setup Script"; WorkingDir: "{app}";flags: postinstall waituntilterminated
